### ISSUE TITLE
Divide by zero error

### ISSUE THREAD

**Issue by cmilr** [cmilr/DeadSimple-Pixel-Perfect-Camera#2]
Script is throwing a division-by-zero error when left with default settings.

**Comment by cmilr** [comment]
Added correct default values plus user input validation to ensure values are always above zero.

**Comment by Jrayp** [comment]
No you made it so that 0 values aren't accepted, and it does nothing for negative values. The script seems to be very inconsistent in general.

**Comment by cmilr** [comment]
It’s just a script I shared, and plenty have found it useful. Feel free to use it, modify it, or just walk away.
